{% set name = "paprika" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/slochower/pAPRika/archive/v{{ version }}.tar.gz
  sha256: 73003e1fe0d25a75ed66585152df30f0605d2c9640882225387a2d66892b2858

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"


requirements:
  host:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python >=3.6
    - numpy
    - scipy
    - setuptools
    - pymbar >=3.0.4
    - mdtraj
    - ambertools

test:
  requires:
    - pytest
  imports:
    - paprika

about:
  home: https://github.com/slochower/pAPRika
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pAPRika is a toolkit for setting up, running, and analyzing free energy molecular dynamics simulations.
  doc_url: https://paprika.readthedocs.io/en/latest/
  dev_url: https://github.com/slochower/pAPRika

extra:
  recipe-maintainers:
    - slochower
    - nhenriksen
