{% set name = "paprika" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/slochower/pAPRika/archive/v{{ version }}.tar.gz
  sha256: 9e34904ebb49abcf6ce19c9435c53fce932135945b4452ceb690fbfd14bb0461 

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"


requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - numpy
    - scipy
    - setuptools
    - pymbar
    - mdtraj
    - ambertools

test:
  requires:
    - pytest
  imports:
    - paprika

about:
  home: https://github.com/slochower/pAPRika
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pAPRika is a toolkit for setting up, running, and analyzing free energy molecular dynamics simulations.
  doc_url: https://paprika.readthedocs.io/en/latest/
  dev_url: https://github.com/slochower/pAPRika

extra:
  recipe-maintainers:
    - slochower
    - nhenriksen
