travis:
  secure:
    BINSTAR_TOKEN: uTuEsTc/mL39d+YtdkQAAEeJnkpgFtHnSOYXP5Kj/Lat1G0+fW14NJgEVtkMk9z5kChZVCAjU7tjMskZSAxhyELD54R5Yg5AXdHoLu3RY67hNUtsG2w5PlbgG8S1IkKWevNFXVFvKEzdUlsC+2ol2SPJgGq3XIt/BY4bfZBA850IzlX7gi2hT2d0R82G7PtuowaOSN+zEmvIqgh7x1mEDK4C238g3PtrOKVaQbr7pDCTIz/ZlsMkEK0/cb2oSsy2l5R3Do3kmv9EgjDoQr1D9n1e7AwLpOt/ekk+6RS4bYIDfm2GNurS2+B4TNcp81nVBJ1sX59u/2m682gobLytrXBaVeBQX1to9Jgsh5XPw0KqWnYahrbWBXiS2BARkuyEVYjEKLMVuiGL5jActmVXZ/h04nBq+WvKowYxeNdt9ykOktfAh7a4geqO4BWP/DmObFDVSvlDQ10FGoqm5jG1sm+F2RcySx9PhMIhb8w4B+wevlzLastMrXpdOXGPvlHR6im3/8deH1A6ehn0sPmKDlKw4H+p4M0VHFJs9hs4I6gwNsdZQEmZf/3GQRe08LKO99IxEMh+fCjPaLZvVKD9Rk/v7tNVx/rsZ8k0Ebqq0y84eaxKXf4pkX8mT3C3BGV89/DffQInF7p1rPCxFwMz7Us1NSrwGuZafGWtWRkfYqE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
